vapusBESecretStorage: 
  filePath: "secrets/be-secret-storage.yaml"
  secret: "vapusdata-be-secret"
vapusBEDbStorage: 
  filePath:  "secrets/be-db-storages.yaml"
  secret:  764ed-secret
vapusBECacheStorage: 
  filePath:  96406-secret
  secret:  a7739-secret
vapusFileStorage: 
  filePath:  96406-secret
  secret:  vapus-demo-bucket-store
JWTAuthnSecrets: 
  filePath: "secrets/jwt-secrets.yaml"
  secret: e7157-secret
networkConfigFile: network/network-config.yaml
serverCerts:
  mtls: False
  caCertFile: "/Users/vikrantsingh/vikrant/workspaces/anekam/vapusdata/vapusdata-ecosystem/vapusdata/local-configs/certs/ca-cert.pem"
  serverCertFile: "/Users/vikrantsingh/vikrant/workspaces/anekam/vapusdata/vapusdata-ecosystem/vapusdata/local-configs/certs/server-cert.pem"
  serverKeyFile: "/Users/vikrantsingh/vikrant/workspaces/anekam/vapusdata/vapusdata-ecosystem/vapusdata/local-configs/certs/server-key.pem"
  clientCertFile: "/Users/vikrantsingh/vikrant/workspaces/anekam/vapusdata/vapusdata-ecosystem/vapusdata/local-configs/certs/client-cert.pem"
  clientKeyFile: "/Users/vikrantsingh/vikrant/workspaces/anekam/vapusdata/vapusdata-ecosystem/vapusdata/local-configs/certs/client-key.pem"
trinoSpecs:
  appSelector: vapusdata-trino
  namespace: vapusdata
  trinoCordDeployment: vapusdata-trino-trino-coordinator
  trinoWorkerDeployment: vapusdata-trino-trino-worker
  trinoCordSvc: "127.0.0.1"
  trinoWorkerSvc: vapusdata-trino-trino-worker
  trinoCordDeploymentContainer: trino-coordinator
  trinoWorkerDeploymentContainer: trino-worker
  trnioWorkerPort: 8080
  trinoCordPort: 8080
  trinoCordSvcPort: 8085
  trinoWorkerSvcPort: 8080
  trinoAppName: vapusdata-trino
  trinoCatalog: vapusdata-trino-trino-catalog
  trinoHost: http://vapusdata@127.0.0.1:8085