vapusBESecretStorage: 
  filePath: "secrets/be-secret-storage.yaml"
  secret: "vapusdata-be-secret"
vapusBEDbStorage: 
  filePath:  "secrets/be-db-storages.yaml"
  secret:  764ed-secret
vapusBEvectorStorage: 
  filePath:  "secrets/be-db-storages.yaml"
  secret:  764ed-secret
vapusBECacheStorage: 
  filePath:  96406-secret
  secret:  a7739-secret
vapusFileStorage: 
  filePath:  96406-secret
  secret:  vapus-demo-bucket-store
JWTAuthnSecrets: 
  filePath: "secrets/jwt-secrets.yaml"
  secret: e7157-secret
serverConfig: 
  port: "9013"
  serviceName: "platform-svc"
  scheme: "http"
  external: "https://demo.vapusdata.com"
datastores: 
localFSPaths:
  domainFiles: local-storage/domains
  dataSourceFiles: local-storage/datasource 
authnSecrets: 
  patfilePathh: "secrets/authn-secrets.yaml"
  secret: 95e79-secret
networkConfigFile: network/network-config.yaml
trinoSpecs:
  appSelector: vapusdata-trino
  namespace: vapusdata
  trinoCordDeployment: vapusdata-trino-trino-coordinator
  trinoWorkerDeployment: vapusdata-trino-trino-worker
  trinoCordSvc: vapusdata-trino-trino
  trinoWorkerSvc: vapusdata-trino-trino-worker
  trinoCordDeploymentContainer: trino-coordinator
  trinoWorkerDeploymentContainer: trino-worker
  trnioWorkerPort: 8080
  trinoCordPort: 8080
  trinoCordSvcPort: 8080
  trinoWorkerSvcPort: 8080
  trinoAppName: vapusdata-trino
  trinoCatalog: vapusdata-trino-trino-catalog
  trinoHost: http://vapusdata@127.0.0.1:8085
serverCerts:
  mtls: False
  caCertFile: "/Users/vikrantsingh/vikrant/workspaces/anekam/vapusdata/vapusdata-ecosystem/vapusdata/local-configs/certs/ca-cert.pem"
  serverCertFile: "/Users/vikrantsingh/vikrant/workspaces/anekam/vapusdata/vapusdata-ecosystem/vapusdata/local-configs/certs/server-cert.pem"
  serverKeyFile: "/Users/vikrantsingh/vikrant/workspaces/anekam/vapusdata/vapusdata-ecosystem/vapusdata/local-configs/certs/server-key.pem"
  clientCertFile: "/Users/vikrantsingh/vikrant/workspaces/anekam/vapusdata/vapusdata-ecosystem/vapusdata/local-configs/certs/client-cert.pem"
  clientKeyFile: "/Users/vikrantsingh/vikrant/workspaces/anekam/vapusdata/vapusdata-ecosystem/vapusdata/local-configs/certs/client-key.pem"
pbacConfig:
  filePath: "config/global-policies-config.yaml"
authnMethod: oidc
baseOs:
  - artifactType: vdc 
    url: "asia-south1-docker.pkg.dev/vapusdata-beta/vapusdata-ecosystem/vapus-containers"
    digest: "sha256:68fb2f56530f752137cd2bb9b06d20eba05971960e13348f5294dd27f3901eda"
    tag: "local_vikrantsingh"
    domainMounts: 
      - "/src"
  - artifactType: dataworker
    url: "asia-south1-docker.pkg.dev/vapusdata-beta/vapusdata-ecosystem/dataworker"
    digest: "sha256:9882be5e2e44b48984b793559b2ebc20a3ca64073b2f9a7807cf7b6e354c96ed"
    tag: "local_vikrantsingh"
    domainMounts: 
      - "/src"
artifactStore:
  filePath: "secrets/artifact-store-secret.yaml"
  secret: ea144-secret
platformBaseAccount:
  platformOwners:
    - vikrant@vapusdata.com
  platformAccount: 
    name: VapusData Sandbox 
    creator: vikrant@vapusdata.com
  platformAccountDomain:
    name: VapusData Sandbox Service Domain
  datamarketplace:
    name: VapusData DataMesh
    creator: vikrant@vapusdata.com