affinity: {}
aistudio:
  artifacts:
    digest: sha256:3835d0ee94c78588cac7a67b8fe4e657ce0741befccec5e85e57c87ee3263918
    image: vapusdata-ecosystem/aistudio
    pullPolicy: IfNotPresent
    tag: v0.0.250
  autoscaling:
    enabled: false
    maxReplicas: 10
    minReplicas: 1
    targetCPUUtilizationPercentage: 80
  containerName: aistudio
  enabled: true
  fullname: aistudio
  name: aistudio
  replicaCount: 1
  resources:
    limits:
      cpu: 512m
      memory: 512Mi
    requests:
      cpu: 256m
      memory: 256Mi
  service:
    grpc:
      name: aistudiogrpc
      port: 9012
      targetPort: 9012
      type: grpc
    svcPort: 9012
    type: ClusterIP
  serviceAccount:
    annotations: null
    clusterRole:
      name: vapusdata-aistudio-master-cr
    clusterRoleBinding:
      name: vapusdata-aistudio-master-crb
    create: true
    name: vapusdata-aistudio-master-sa
  volumePaths:
    certMount:
      name: tls-secrets
      path: /certs
    networkConfig:
      path: /network
    secretsMount:
      name: aistudio-secrets
      path: /secrets
    serviceConfig:
      name: aistudio-service-config
      path: /config
app:
  podMountPath: /data/vapusdata
auth:
  oidc:
    callback: /auth/callback
    login: /login
    logout: /logout
genServiceAccount:
  annotations: null
  clusterRole:
    name: vapusdata-gen-cr
  clusterRoleBinding:
    name: vapusdata-gen-crb
  create: true
  name: vapusdata-gen-sa
imagePullSecrets:
- name: vapusdata-ecosystem-pls
ingress:
  annotations: {}
  className: gce
  enabled: true
  name: vapusdata-gateway
  paths:
  - backend:
      service:
        name: webapp
        port:
          number: 9013
    path: /
    pathType: Prefix
nabhikserver:
  artifacts:
    digest: sha256:2e45557ef4368aaccd830263db22d323a5e74cd0e731492e6614b358a1d97540
    image: vapusdata-ecosystem/nabhikserver
    pullPolicy: IfNotPresent
    tag: v0.0.250
  autoscaling:
    enabled: false
    maxReplicas: 10
    minReplicas: 1
    targetCPUUtilizationPercentage: 80
  containerName: nabhikserver
  enabled: true
  fullname: nabhikserver
  name: nabhikserver
  replicaCount: 1
  resources:
    limits:
      cpu: 512m
      memory: 512Mi
    requests:
      cpu: 256m
      memory: 256Mi
  service:
    grpc:
      name: dpsvcgrpc
      port: 9012
      targetPort: 9012
      type: grpc
    svcPort: 9012
    type: ClusterIP
  volumePaths:
    certMount:
      name: tls-secrets
      path: /certs
    networkConfig:
      path: /network
    secretsMount:
      name: nabhikserver-secrets
      path: /secrets
    serviceConfig:
      name: nabhikserver-service-config
      path: /config
nabrunners:
  artifacts:
    digest: sha256:e3c7ec09ec303a71701f7bde8acfb1452591de1a4f2ad59670d26faf023ece3e
    image: vapusdata-ecosystem/nabrunners
    pullPolicy: IfNotPresent
    tag: v0.0.250
  autoscaling:
    enabled: false
    maxReplicas: 10
    minReplicas: 1
    targetCPUUtilizationPercentage: 80
  concurrentRunners: 50
  containerName: nabrunners
  enabled: true
  fullname: nabrunners
  name: nabrunners
  replicaCount: 1
  resources:
    limits:
      cpu: 512m
      memory: 512Mi
    requests:
      cpu: 256m
      memory: 256Mi
  service:
    http:
      name: aistudiogrpc
      port: 9020
      targetPort: 9020
      type: http
    svcPort: 9020
    type: ClusterIP
  serviceAccount:
    annotations: null
    clusterRole:
      name: vapusdata-nabrunners-master-cr
    clusterRoleBinding:
      name: vapusdata-nabrunners-master-crb
    create: true
    name: vapusdata-nabrunners-master-sa
  volumePaths:
    certMount:
      name: tls-secrets
      path: /certs
    networkConfig:
      path: /network
    secretsMount:
      name: nabrunners-secrets
      path: /secrets
    serviceConfig:
      name: nabrunners-service-config
      path: /config
nodeSelector: {}
platform:
  artifacts:
    digest: sha256:df156b7b36a2c1317f01255f4c3223783e25f7a32684a872fafe8e0271dec8bc
    image: vapusdata-ecosystem/platform
    pullPolicy: IfNotPresent
    tag: v0.0.250
  autoscaling:
    enabled: true
    maxReplicas: 10
    minReplicas: 1
    targetCPUUtilizationPercentage: 80
  containerName: platform
  enabled: true
  fullname: platform
  name: platform
  replicaCount: 1
  resources:
    limits:
      cpu: 512m
      memory: 512Mi
    requests:
      cpu: 256m
      memory: 256Mi
  service:
    grpc:
      name: platformgrpc
      port: 9012
      targetPort: 9012
      type: grpc
    svcPort: 9012
    type: ClusterIP
  serviceAccount:
    annotations: null
    clusterRole:
      name: vapusdata-platform-master-cr
    clusterRoleBinding:
      name: vapusdata-platform-master-crb
    create: true
    name: vapusdata-platform-master-sa
  volumePaths:
    certMount:
      name: tls-secrets
      path: /certs
    networkConfig:
      name: network-config
      path: /network
    policyConfig:
      path: /policy
    secretsMount:
      filename: be-secret-storage.yaml
      name: platform-secrets
      path: /secrets
    serviceConfig:
      name: platform-service-config
      path: /config
tolerations: []
vapusDataArtifacts:
  dataworker:
    digest: sha256:f6898ac7e89d72663533e9f3bbf77a24bc396f4b48ac6bca020b521988acf551
    image: asia-south1-docker.pkg.dev/vapusdata-beta/vapusdata-ecosystem/dataworker
    tag: v0.0.250
  vdc:
    digest: sha256:d12166892b396f523f8c4c24822243fb7301f384d1ddc0c5d32984254860bd7f
    image: asia-south1-docker.pkg.dev/vapusdata-beta/vapusdata-ecosystem/vapus-containers
    tag: v0.0.250
vapusaigateway:
  artifacts:
    digest: sha256:0ab0d81e3ed03c85114613a15189a5d899de614afb534a309ec8d3067bb51b6d
    image: vapusdata-ecosystem/vapusaigateway
    pullPolicy: IfNotPresent
    tag: v0.0.250
  autoscaling:
    enabled: false
    maxReplicas: 10
    minReplicas: 1
    targetCPUUtilizationPercentage: 80
  containerName: vapusaigateway
  enabled: true
  fullname: vapusaigateway
  name: vapusaigateway
  replicaCount: 2
  resources:
    limits:
      cpu: 512m
      memory: 512Mi
    requests:
      cpu: 256m
      memory: 256Mi
  service:
    http:
      name: vapusaigateway
      port: 9013
      targetPort: 9013
      type: http
    svcPort: 9013
    type: ClusterIP
  volumePaths:
    certMount:
      name: tls-secrets
      path: /certs
    networkConfig:
      path: /network
    secretsMount:
      name: aistudio-secrets
      path: /secrets
    serviceConfig:
      name: aistudio-service-config
      path: /config
vapusdata:
  globalConfigs:
    networkConfig:
      fileName: network-config.yaml
      name: network-config
    policyConfig:
      fileName: policy/global-policies-config.yaml
      name: global-policies-config
  globalSecrets:
    backend:
      secretStore: be-secret-storage
      secretStoreFileName: be-secret-storage.yaml
    certs:
      tlsSecret: vapusdatademotls
  registry: asia-south1-docker.pkg.dev/vapusdata-beta/
webapp:
  artifacts:
    digest: sha256:2cb6ffb5fbd0f829a866ab6d88ddea2c7534b52db4b4997b41eff82ebbe15727
    image: vapusdata-ecosystem/webapp
    pullPolicy: IfNotPresent
    tag: v0.0.250
  autoscaling:
    enabled: false
    maxReplicas: 10
    minReplicas: 2
    targetCPUUtilizationPercentage: 80
  containerName: webapp
  enabled: true
  fullname: webapp
  name: webapp
  replicaCount: 2
  resources:
    limits:
      cpu: 512m
      memory: 512Mi
    requests:
      cpu: 256m
      memory: 256Mi
  service:
    http:
      name: webapp
      port: 9013
      targetPort: 9013
      type: http
    svcPort: 9013
    type: ClusterIP
  volumePaths:
    certMount:
      name: tls-secrets
      path: /certs
    networkConfig:
      path: /network
    serviceConfig:
      name: webapp-service-config
      path: /config
