name: Build, Verify and Release microservices

on:
  push:
    tags:
      - 'v*.*.*'
    branches:
      - main
  pull_request:
    types: [closed]
    branches:
      - main

jobs:
  proto-linter:
    uses: vapusdata-ecosystem/vapusdata/.github/workflows/proto-lint.yaml@main
  webapp-svc-pipeline:
    if: github.event_name == 'push' && startsWith(github.ref, 'refs/tags/')
    uses: vapusdata-ecosystem/vapusdata/.github/workflows/webapp_workflows.yaml@main
    with:
      oci-registry: ${{ vars.VAPUS_BETA_GAR }}
      tag: ${{ github.ref }}
    secrets:
      signing-key: ${{ secrets.COSIGN_KEY }}
      signing-password: ${{ secrets.COSIGN_PASSWORD }}
      oci-username: ${{ secrets.GAR_DEV_USERNAME }}
      oci-password: ${{ secrets.VAPUS_BETA_GAR_PASS }}
  aistudio-svc-pipeline:
    if: github.event_name == 'push' && startsWith(github.ref, 'refs/tags/')
    uses: vapusdata-ecosystem/vapusdata/.github/workflows/aistudio_svc_workflows.yaml@main
    with:
      oci-registry: ${{ vars.VAPUS_BETA_GAR }}
      tag: ${{ github.ref }}
    secrets:
      signing-key: ${{ secrets.COSIGN_KEY }}
      signing-password: ${{ secrets.COSIGN_PASSWORD }}
      oci-username: ${{ secrets.GAR_DEV_USERNAME }}
      oci-password: ${{ secrets.VAPUS_BETA_GAR_PASS }}
  aigateway-svc-pipeline:
    if: github.event_name == 'push' && startsWith(github.ref, 'refs/tags/')
    uses: vapusdata-ecosystem/vapusdata/.github/workflows/aigateway_svc_workflows.yaml@main
    with:
      oci-registry: ${{ vars.VAPUS_BETA_GAR }}
      tag: ${{ github.ref }}
    secrets:
      signing-key: ${{ secrets.COSIGN_KEY }}
      signing-password: ${{ secrets.COSIGN_PASSWORD }}
      oci-username: ${{ secrets.GAR_DEV_USERNAME }}
      oci-password: ${{ secrets.VAPUS_BETA_GAR_PASS }}
  # vapusctl-svc-pipeline:
  #   if: github.event_name == 'push' && startsWith(github.ref, 'refs/tags/')
  #   uses: vapusdata-ecosystem/vapusdata/.github/workflows/vapusctl_workflows.yaml@main
  #   with:
  #     oci-registry: ${{ vars.VAPUS_BETA_GAR }}
  #     pub-operator-repo: ${{ vars.PUB_OPERATOR_REPO }}
  #     tag: ${{ github.ref }}
  #   secrets:
  #     signing-key: ${{ secrets.COSIGN_KEY }}
  #     signing-password: ${{ secrets.COSIGN_PASSWORD }}
  #     oci-username: ${{ secrets.GAR_DEV_USERNAME }}
  #     oci-password: ${{ secrets.VAPUS_BETA_GAR_PASS }}
  #     pub-operator-repo-pat: ${{ secrets.PUB_OPERATOR_PACKAGE_PAT }}

  aggregate-builds:
    if: github.event_name == 'push' && startsWith(github.ref, 'refs/tags/')
    runs-on: ubuntu-latest
    needs:
      - proto-linter
      - webapp-svc-pipeline
      - aistudio-svc-pipeline
      - aigateway-svc-pipeline
    steps:
      - name: Download Webapp OCI Tag
        uses: actions/download-artifact@v4
        with:
          name: webapp-tag-artifacts

      - name: Download Webapp OCI Digest
        uses: actions/download-artifact@v4
        with:
          name: webapp-digest-artifacts

      - name: Download AIGateway OCI Tag
        uses: actions/download-artifact@v4
        with:
          name: aigateway-tag-artifacts

      - name: Download AIGateway OCI Digest
        uses: actions/download-artifact@v4
        with:
          name: aigateway-digest-artifacts

      - name: Download AISTUDIO OCI Tag
        uses: actions/download-artifact@v4
        with:
          name: aistudio-tag-artifacts
      - name: Download AISTUDIO OCI Digest
        uses: actions/download-artifact@v4
        with:
          name: aistudio-digest-artifacts

      - name: Read All artifacts
        id: read-oci-tags-digests
        run: |
          echo cat $(dataworker-digest.txt)
          AISTUDIOTAG=$(cat aistudio-tag.txt)
          echo "AISTUDIOTAG=$AISTUDIOTAG" >> $GITHUB_OUTPUT
          echo "AISTUDIOTAG: $AISTUDIOTAG"
          AISTUDIODIGEST=$(cat aistudio-digest.txt)
          echo "AISTUDIODIGEST=$AISTUDIODIGEST" >> $GITHUB_OUTPUT
          echo "AISTUDIODIGEST: $AISTUDIODIGEST"
          WEBAPPTAG=$(cat webapp-tag.txt)
          echo "WEBAPPTAG=$WEBAPPTAG" >> $GITHUB_OUTPUT
          echo "WEBAPPTAG: $WEBAPPTAG"
          WEBAPPDIGEST=$(cat webapp-digest.txt)
          echo "WEBAPPDIGEST=$WEBAPPDIGEST" >> $GITHUB_OUTPUT
          echo "WEBAPPDIGEST: $WEBAPPDIGEST"
          AIGATEWAYTAG=$(cat aigateway-tag.txt)
          echo "AIGATEWAYTAG=$AIGATEWAYTAG" >> $GITHUB_OUTPUT
          echo "AIGATEWAYTAG: $AIGATEWAYTAG"
          AIGATEWAYDIGEST=$(cat aigateway-digest.txt)
          echo "AIGATEWAYDIGEST=$AIGATEWAYDIGEST" >> $GITHUB_OUTPUT
          echo "AIGATEWAYDIGEST: $AIGATEWAYDIGEST"
      - name: Debug Outputs
        run: |
          echo "AISTUDIOTAG: $AISTUDIOTAG"
          echo "AISTUDIODIGEST: $AISTUDIODIGEST"
          echo "WEBAPPTAG: $WEBAPPTAG"
          echo "WEBAPPDIGEST: $WEBAPPDIGEST"
          echo "AIGATEWAYTAG: $AIGATEWAYTAG"
          echo "AIGATEWAYDIGEST: $AIGATEWAYDIGEST"
          echo $GITHUB_OUTPUT
          echo "==========================================="
          echo "${{ steps.read-oci-tags-digests.outputs.PLATFORMDIGEST }}"
    outputs:
      AISTUDIOTAG : ${{ steps.read-oci-tags-digests.outputs.AISTUDIOTAG }}
      AISTUDIODIGEST : ${{ steps.read-oci-tags-digests.outputs.AISTUDIODIGEST }}
      WEBAPPTAG : ${{ steps.read-oci-tags-digests.outputs.WEBAPPTAG }}
      WEBAPPDIGEST : ${{ steps.read-oci-tags-digests.outputs.WEBAPPDIGEST }}
      AIGATEWAYTAG : ${{ steps.read-oci-tags-digests.outputs.AIGATEWAYTAG }}
      AIGATEWAYDIGEST : ${{ steps.read-oci-tags-digests.outputs.AIGATEWAYDIGEST }}
      
  helmchart-build-app:
    if: github.event_name == 'push' && startsWith(github.ref, 'refs/tags/')
    uses: vapusdata-ecosystem/vapusdata/.github/workflows/build_helmchart_workflows.yaml@main
    needs: aggregate-builds
    with:
      vapus-aistudio-tag: ${{ needs.aggregate-builds.outputs.AISTUDIOTAG }}
      vapus-aistudio-digest: ${{ needs.aggregate-builds.outputs.AISTUDIODIGEST }}
      webapp-tag: ${{ needs.aggregate-builds.outputs.WEBAPPTAG }}
      webapp-digest: ${{ needs.aggregate-builds.outputs.WEBAPPDIGEST }}
      aigateway-tag: ${{ needs.aggregate-builds.outputs.AIGATEWAYTAG }}
      aigateway-digest: ${{ needs.aggregate-builds.outputs.AIGATEWAYDIGEST }}
      upload-artifact: false
      tag: ${{ github.ref }}
      oci-registry: ${{ vars.VAPUS_BETA_GAR }}
    secrets:
      signing-key: ${{ secrets.COSIGN_KEY }}
      signing-password: ${{ secrets.COSIGN_PASSWORD }}
      oci-username: ${{ secrets.GAR_DEV_USERNAME }}
      oci-password: ${{ secrets.VAPUS_BETA_GAR_PASS }}

  helmchart-release-app:
    if: (github.event.pull_request.merged == true && github.event.pull_request.base.ref == 'main')
    uses: vapusdata-ecosystem/vapusdata/.github/workflows/release_helmchart_workflows.yaml@main
    with:
      upload-artifact: true
      tag: ${{ github.ref }}
      oci-registry: ${{ vars.VAPUS_BETA_GAR }}
      pub-operator-repo: ${{ vars.PUB_OPERATOR_REPO }}
    secrets:
      signing-key: ${{ secrets.COSIGN_KEY }}
      signing-password: ${{ secrets.COSIGN_PASSWORD }}
      oci-username: ${{ secrets.GAR_DEV_USERNAME }}
      oci-password: ${{ secrets.VAPUS_BETA_GAR_PASS }}
      pub-operator-repo-pat: ${{ secrets.PUB_OPERATOR_PACKAGE_PAT }}

    
    